export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';
export const FILTER_PRICE_SET = 'FILTER_PRICE_SET';
export const SORT_TYPE_UPDATED = 'SORT_TYPE_UPDATED'
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED'
export const UPDATED_SEARCH_KEYWORD = 'UPDATED_SEARCH_KEYWORD';

export const ADDED_ITEM_TO_CART = 'ADDED_ITEM_TO_CART';
export const UPDATED_ITEM_IN_CART = 'UPDATED_ITEM_IN_CART';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';



